project:
  type: website
  output-dir: docs

website:
  title: "Ecosystem and Socioeconomic Profiles"
  navbar:
    background: "#003366"
    search: true
    left:
      - text: "Overview"
        href: index.md
      - text: "The 4 Steps"
        href: content/steps.md
      - text: "ESPs in Action"
        href: content/action.md
      - text: "National Coordination"
        href: content/coordination.md
      - text: "FAQs"
        href: content/faqs.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
