project:
  type: website
  output-dir: docs

website:
  title: "Ecosystem and Socioeconomic Profiles"
  navbar:
    background: "#003366"
    logo: images/esp-logo.png
    search: true
    right:
      - text: "Overview"
        href: content/overview.qmd
      - text: "The 4 Steps"
        href: content/steps.qmd
      - text: "ESPs in Action"
        href: content/action.qmd
      - text: "National Coordination"
        href: content/coordination.qmd
      - text: "FAQs"
        href: content/faqs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-expand: true
